accelerator: cpu
precision: "bf16-mixed"
max_epochs: 500
max_steps: 250000
log_every_n_steps: 10
num_nodes: 1
gpus_per_node: 4
limit_val_batches: 0.25
check_val_every_n_epoch: 10
val_check_interval: 2000
accumulate_grad_batches: 8
clip_grad: 0.5