model_checkpoint:
  # dirpath: "${paths.checkpoints_dir}"
  filename: "{epoch:03d}_{val_loss:.2f}"
  monitor: "val_loss"
  mode: "min"
  save_top_k: 1
  save_last: True

early_stopping:
  monitor: "val_loss"
  patience: 5
  mode: "min"

embed_monitor:
  check_interval: 100