model_checkpoint:
  # dirpath: "${paths.checkpoints_dir}"
  filename: "{epoch:03d}_{val_loss:.2f}"
  monitor: "val_loss"
  mode: "min"
  save_top_k: 3
  save_last: True

early_stopping:
  monitor: "val_loss"
  patience: 10
  mode: "min"